name: CI

on:
  push:

jobs:
  go:
    name: Go Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.5'
          cache: true
      - name: Run build
        run: make build
      - name: Run tests
        run: make test
