name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.5'
          cache: true
      - name: Run build
        run: make build
      - name: Run tests
        run: make test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.5'
          cache: true
      - name: Run lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: v1.55.2 # The version of golangci-lint to use.
